site_name: Hit By A Bus Plan
site_description: What to do if something happens to Tony Green
site_author: Tony Green

# Repository (if hosting on GitHub)
# repo_name: username/hit-by-a-bus
# repo_url: https://github.com/username/hit-by-a-bus

# Content directory relative to this mkdocs.yml file
docs_dir: ../content-work

# Output directory - will be created relative to this mkdocs.yml file
site_dir: ../output/site

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  favicon: styles/favicon.png
  logo: styles/favicon.png
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Navigation structure
nav:
  - 'Home': 'index.md'
  - 'Start Here': '01-overview.md'
  - 'Personal Info': '02-personal-info.md'
  - 'Emergency Contacts': '03-emergency-contacts.md'
  - 'Digital Access': '04-digital-access.md'
  - 'Household & Finances': '05-household-and-finances.md'
  - 'Legal & Medical': '06-legal-and-medical.md'
  - 'Jobs & Work': '07-jobs.md'
  - 'Infrastructure & Systems': '08-infrastructure-and-computers.md'
  - 'Ongoing Commitments': '09-ongoing-commitments.md'
  - 'Personal Wishes': '10-personal-wishes.md'
  - 'Documents & Safe': '11-safe-and-physical-docs.md'

# Plugins
plugins:
  - search:
      lang: en
  # PDF generation handled by separate script using weasyprint

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3

# Additional CSS
extra_css:
  - styles/print.css

# Extra configuration
extra:
  generator: false  # Remove "Made with Material for MkDocs"
  social: []  # No social links needed for this type of site

# Copyright
copyright: Personal Emergency Plan
